apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: incidentiq
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - api.yaml
  - worker.yaml
  - web.yaml
