apiVersion: v1
kind: Secret
metadata:
  name: incidentiq-secrets
  namespace: incidentiq
type: Opaque
stringData:
  DATABASE_URL: postgres://incidentiq:incidentiq@postgres:5432/incidentiq?sslmode=disable
  JIRA_USERNAME: ""
  JIRA_API_TOKEN: ""
  DYNATRACE_WEBHOOK_SECRET: ""
  ELK_WEBHOOK_SECRET: ""
  GENERIC_WEBHOOK_SECRET: ""
